apiVersion: v2
name: postgres-operator
version: 1.12.2
appVersion: 1.12.2
annotations:
  catalog.cattle.io/display-name: "Zalando Postgres Operator"
  catalog.cattle.io/release-name: postgres-operator
  catalog.cattle.io/namespace: postgres-operator
home: https://github.com/zalando/postgres-operator
icon: https://github.com/zalando/postgres-operator/raw/master/docs/diagrams/logo.png
description: Postgres Operator creates and manages PostgreSQL clusters running in Kubernetes
keywords:
- postgres
- operator
- cloud-native
- patroni
- spilo
maintainers:
- name: Zalando
  email: opensource@zalando.de
sources:
- https://github.com/zalando/postgres-operator
engine: gotpl
