apiVersion: v1
entries:
  postgres-operator:
  - annotations:
      catalog.cattle.io/display-name: Zalando Postgres Operator
      catalog.cattle.io/namespace: postgres-operator
      catalog.cattle.io/release-name: postgres-operator
    apiVersion: v2
    appVersion: 1.12.2
    created: "2024-06-14T13:01:58.119021844+02:00"
    description: Postgres Operator creates and manages PostgreSQL clusters running
      in Kubernetes
    digest: 4ad9cd38148010b4e72d73f5a8adbc4835cd9986f518896b07a572de054c4c36
    home: https://github.com/zalando/postgres-operator
    icon: https://github.com/zalando/postgres-operator/raw/master/docs/diagrams/logo.png
    keywords:
    - postgres
    - operator
    - cloud-native
    - patroni
    - spilo
    maintainers:
    - email: opensource@zalando.de
      name: Zalando
    name: postgres-operator
    sources:
    - https://github.com/zalando/postgres-operator
    urls:
    - postgres-operator-1.12.2.tgz
    version: 1.12.2
  - annotations:
      catalog.cattle.io/display-name: Zalando Postgres Operator
      catalog.cattle.io/namespace: postgres-operator
      catalog.cattle.io/release-name: postgres-operator
    apiVersion: v2
    appVersion: 1.11.0
    created: "2024-06-14T13:01:58.116835533+02:00"
    description: Postgres Operator creates and manages PostgreSQL clusters running
      in Kubernetes
    digest: 1155aa3e34234d517da1279281cadb4287a386e7590834901dc49a90fd4467f5
    home: https://github.com/zalando/postgres-operator
    icon: https://github.com/zalando/postgres-operator/raw/master/docs/diagrams/logo.png
    keywords:
    - postgres
    - operator
    - cloud-native
    - patroni
    - spilo
    maintainers:
    - email: opensource@zalando.de
      name: Zalando
    name: postgres-operator
    sources:
    - https://github.com/zalando/postgres-operator
    urls:
    - postgres-operator-1.11.0.tgz
    version: 1.11.0
  - apiVersion: v2
    appVersion: 1.9.0
    created: "2024-06-14T13:01:58.121424187+02:00"
    description: Postgres Operator creates and manages PostgreSQL clusters running
      in Kubernetes
    digest: 64df90c898ca591eb3a330328173ffaadfbf9ddd474d8c42ed143edc9e3f4276
    home: https://github.com/zalando/postgres-operator
    keywords:
    - postgres
    - operator
    - cloud-native
    - patroni
    - spilo
    maintainers:
    - email: opensource@zalando.de
      name: Zalando
    name: postgres-operator
    sources:
    - https://github.com/zalando/postgres-operator
    urls:
    - postgres-operator-1.9.0.tgz
    version: 1.9.0
  - apiVersion: v2
    appVersion: 1.8.2
    created: "2024-06-14T13:01:58.119913938+02:00"
    description: Postgres Operator creates and manages PostgreSQL clusters running
      in Kubernetes
    digest: f77ffad2e98b72a621e5527015cf607935d3ed688f10ba4b626435acb9631b5b
    home: https://github.com/zalando/postgres-operator
    keywords:
    - postgres
    - operator
    - cloud-native
    - patroni
    - spilo
    maintainers:
    - email: opensource@zalando.de
      name: Zalando
    name: postgres-operator
    sources:
    - https://github.com/zalando/postgres-operator
    urls:
    - postgres-operator-1.8.2.tgz
    version: 1.8.2
generated: "2024-06-14T13:01:58.114142843+02:00"
