apiVersion: v1
entries:
  postgres-operator:
  - annotations:
      catalog.cattle.io/display-name: Zalando Postgres Operator
      catalog.cattle.io/namespace: postgres-operator
      catalog.cattle.io/release-name: postgres-operator
    apiVersion: v2
    appVersion: 1.12.2
    created: "2024-06-14T13:15:29.007016277+02:00"
    description: Postgres Operator creates and manages PostgreSQL clusters running
      in Kubernetes
    digest: 2efe8057a8625e7979cc1723e0587296fae4a1fc9f8fddc02bc61e7962e7fb83
    home: https://github.com/zalando/postgres-operator
    icon: https://github.com/zalando/postgres-operator/raw/master/docs/diagrams/logo.png
    keywords:
    - postgres
    - operator
    - cloud-native
    - patroni
    - spilo
    maintainers:
    - email: opensource@zalando.de
      name: Zalando
    name: postgres-operator
    sources:
    - https://github.com/zalando/postgres-operator
    urls:
    - postgres-operator-1.12.2.tgz
    version: 1.12.2
  - annotations:
      catalog.cattle.io/display-name: Zalando Postgres Operator
      catalog.cattle.io/namespace: postgres-operator
      catalog.cattle.io/release-name: postgres-operator
    apiVersion: v2
    appVersion: 1.11.0
    created: "2024-06-14T13:15:29.003617446+02:00"
    description: Postgres Operator creates and manages PostgreSQL clusters running
      in Kubernetes
    digest: 2809931dbf8e27d17cf15f355419a16929b5a03ea30e239b0a2867890b2c4967
    home: https://github.com/zalando/postgres-operator
    icon: https://github.com/zalando/postgres-operator/raw/master/docs/diagrams/logo.png
    keywords:
    - postgres
    - operator
    - cloud-native
    - patroni
    - spilo
    maintainers:
    - email: opensource@zalando.de
      name: Zalando
    name: postgres-operator
    sources:
    - https://github.com/zalando/postgres-operator
    urls:
    - postgres-operator-1.11.0.tgz
    version: 1.11.0
  - apiVersion: v2
    appVersion: 1.9.0
    created: "2024-06-14T13:15:29.009908036+02:00"
    description: Postgres Operator creates and manages PostgreSQL clusters running
      in Kubernetes
    digest: 64df90c898ca591eb3a330328173ffaadfbf9ddd474d8c42ed143edc9e3f4276
    home: https://github.com/zalando/postgres-operator
    keywords:
    - postgres
    - operator
    - cloud-native
    - patroni
    - spilo
    maintainers:
    - email: opensource@zalando.de
      name: Zalando
    name: postgres-operator
    sources:
    - https://github.com/zalando/postgres-operator
    urls:
    - postgres-operator-1.9.0.tgz
    version: 1.9.0
  - apiVersion: v2
    appVersion: 1.8.2
    created: "2024-06-14T13:15:29.00855661+02:00"
    description: Postgres Operator creates and manages PostgreSQL clusters running
      in Kubernetes
    digest: f77ffad2e98b72a621e5527015cf607935d3ed688f10ba4b626435acb9631b5b
    home: https://github.com/zalando/postgres-operator
    keywords:
    - postgres
    - operator
    - cloud-native
    - patroni
    - spilo
    maintainers:
    - email: opensource@zalando.de
      name: Zalando
    name: postgres-operator
    sources:
    - https://github.com/zalando/postgres-operator
    urls:
    - postgres-operator-1.8.2.tgz
    version: 1.8.2
generated: "2024-06-14T13:15:29.00054639+02:00"
